# Generated by Django 6.0.3 on 2026-05-08 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pyme',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employed_pymes', to=settings.AUTH_USER_MODEL),
        ),
    ]
