# Generated by Django 6.0.3 on 2026-05-12 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='get_requests_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='get_requests_count_reset_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
