# Generated by Django 6.0.3 on 2026-08-11 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyme', '0003_order_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PymeEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee'), ('inventory', 'Inventory')], default='employee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='pyme.pyme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyme_employments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pyme', 'user'), name='unique_user_per_pyme')],
            },
        ),
    ]
