# Generated by Django 6.0.3 on 2026-05-12 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyme', '0003_order_created_at'),
        ('stock', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='pyme',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='pyme.pyme'),
        ),
    ]
