# Generated by Django 6.0.3 on 2026-08-10 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyme', '0003_order_created_at'),
        ('stock', '0004_alter_menu_pyme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='pyme',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='pyme.pyme'),
        ),
    ]
