# Generated by Django 6.0.3 on 2026-05-12 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonthlySales",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("month", models.CharField(max_length=20)),
                ("sales", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="MostSeenProducts",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("views", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MostSoldProducts",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("quantity_sold", models.IntegerField()),
                ("profit", models.FloatField()),
            ],
        ),
    ]

