# Generated by Django 6.0.3 on 2026-05-12 00:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyme", "0002_product_get_requests_count_and_more"),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlysales",
            name="pyme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_sales_metrics",
                to="pyme.pyme",
            ),
        ),
        migrations.AddField(
            model_name="mostseenproducts",
            name="pyme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="most_seen_product_metrics",
                to="pyme.pyme",
            ),
        ),
        migrations.AddField(
            model_name="mostsoldproducts",
            name="pyme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="most_sold_product_metrics",
                to="pyme.pyme",
            ),
        ),
        migrations.CreateModel(
            name="MostSoldCategories",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=100)),
                ("quantity_sold", models.IntegerField()),
                ("profit", models.FloatField()),
                (
                    "pyme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="most_sold_category_metrics",
                        to="pyme.pyme",
                    ),
                ),
            ],
        ),
    ]

