# Generated by Django 6.0.3 on 2026-03-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_forum_users_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
