# Generated by Django 6.0.3 on 2026-04-08 16:44

import apps.user.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_code_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 8, 17, 14, 35, 836092, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default=apps.user.models.generate_code, max_length=6, null=True),
        ),
    ]
