# Generated by Django 6.0.3 on 2026-03-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
